# Generated by Django 2.1.1 on 2018-08-31 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Championship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField(verbose_name='YYYY')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('logo', models.FileField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='championship',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='milestone.Team'),
        ),
    ]
