# Generated by Django 2.1.1 on 2018-09-15 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('grade', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('brief', models.CharField(max_length=2000, null=True)),
                ('duration', models.DurationField(null=True)),
                ('publishedDate', models.DateTimeField(null=True)),
                ('roleCount', models.SmallIntegerField(default=0)),
                ('isDetective', models.BooleanField(default=False)),
                ('reasoningGrade', models.FloatField(default=0)),
                ('storyGrade', models.FloatField(default=0)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Plays', to='reasoning.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('brief', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(choices=[('f', 'female'), ('m', 'male')], max_length=2, null=True)),
                ('play', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='reasoning.Play')),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('grade', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='play',
            name='authorRepresentative',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='representativePlays', to='reasoning.Studio'),
        ),
        migrations.AddField(
            model_name='play',
            name='platforms',
            field=models.ManyToManyField(related_name='Plays', to='reasoning.Platform'),
        ),
        migrations.AddField(
            model_name='play',
            name='studio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Plays', to='reasoning.Studio'),
        ),
        migrations.AddField(
            model_name='play',
            name='studioRepresentative',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='representativePlays', to='reasoning.Author'),
        ),
        migrations.AddField(
            model_name='author',
            name='studio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authors', to='reasoning.Studio'),
        ),
    ]
