# Generated by Django 2.1.1 on 2018-09-27 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reasoning', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='play',
        ),
        migrations.AddField(
            model_name='play',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='plays', to='reasoning.Tag'),
        ),
    ]
