# Generated by Django 2.1.1 on 2018-09-21 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reasoning', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': '作者', 'verbose_name_plural': '作者'},
        ),
        migrations.AlterModelOptions(
            name='platform',
            options={'verbose_name': '游戏平台', 'verbose_name_plural': '游戏平台'},
        ),
        migrations.AlterModelOptions(
            name='play',
            options={'verbose_name': '剧本', 'verbose_name_plural': '剧本'},
        ),
        migrations.AlterModelOptions(
            name='playcomment',
            options={'verbose_name': '剧本评论', 'verbose_name_plural': '剧本评论'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': '角色', 'verbose_name_plural': '角色'},
        ),
        migrations.AlterModelOptions(
            name='studio',
            options={'verbose_name': '工作室', 'verbose_name_plural': '工作室'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '标签', 'verbose_name_plural': '标签'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AlterField(
            model_name='author',
            name='brief',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='gender',
            field=models.CharField(blank=True, choices=[('f', 'female'), ('m', 'male')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='studio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authors', to='reasoning.Studio'),
        ),
        migrations.AlterField(
            model_name='play',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Plays', to='reasoning.Author'),
        ),
        migrations.AlterField(
            model_name='play',
            name='brief',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='play',
            name='platforms',
            field=models.ManyToManyField(blank=True, null=True, related_name='Plays', to='reasoning.Platform'),
        ),
        migrations.AlterField(
            model_name='play',
            name='publishedDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='play',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publishedPlays', to='reasoning.Studio'),
        ),
        migrations.AlterField(
            model_name='play',
            name='studio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Plays', to='reasoning.Studio'),
        ),
        migrations.AlterField(
            model_name='playcomment',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playcomment',
            name='play',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reasoning.Play'),
        ),
        migrations.AlterField(
            model_name='role',
            name='brief',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='gender',
            field=models.CharField(blank=True, choices=[('f', 'female'), ('m', 'male')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='play',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='reasoning.Play'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='brief',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='play',
            field=models.ManyToManyField(blank=True, to='reasoning.Play'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('f', 'female'), ('m', 'male')], max_length=2, null=True),
        ),
    ]
